apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "order-service.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "order-service.labels" . | nindent 4 }}
data:
  HTTP_ADDR: ":8080"
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
  DB_NAME: {{ .Values.database.name | quote }}
  DB_USER: {{ .Values.database.user | quote }}
  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
  CACHE_TTL: {{ .Values.cacheTTL | quote }}
  REGION: {{ .Values.region | quote }}
