apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "order-service.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{- include "order-service.selectorLabels" . | nindent 6 }}
  policyTypes: ["Ingress", "Egress"]
  ingress:
    - from:
        - ipBlock:
            cidr: 35.191.0.0/16
        - ipBlock:
            cidr: 130.211.0.0/22
      ports:
        - protocol: TCP
          port: 8080
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
      ports:
        - protocol: TCP
          port: 8080
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: gmp-system
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - ipBlock:
            cidr: {{ .Values.database.cidr | quote }}
      ports:
        - protocol: TCP
          port: {{ .Values.database.port }}
    - to:
        - ipBlock:
            cidr: {{ printf "%s/32" .Values.redis.host | quote }}
      ports:
        - protocol: TCP
          port: {{ .Values.redis.port }}
    - to:
        - ipBlock:
            cidr: {{ .Values.billingApi.cidr | quote }}
      ports:
        - protocol: TCP
          port: {{ .Values.billingApi.port }}
