apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "order-service.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 75%
  unhealthyPodEvictionPolicy: IfHealthyBudget
  selector:
    matchLabels:
      {{- include "order-service.selectorLabels" . | nindent 6 }}
