apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: order-service-database
  namespace: {{ .Release.Namespace }}
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.projectId }}/secrets/{{ .Values.database.secretId }}/versions/latest"
        path: "database-password"
---
apiVersion: secret-sync.gke.io/v1
kind: SecretSync
metadata:
  name: order-service-db
  namespace: {{ .Release.Namespace }}
spec:
  serviceAccountName: {{ include "order-service.name" . }}
  secretProviderClassName: order-service-database
  secretObject:
    type: Opaque
    data:
      - sourcePath: database-password
        targetKey: password
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: order-service-cache
  namespace: {{ .Release.Namespace }}
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.projectId }}/secrets/{{ .Values.redis.authSecretId }}/versions/latest"
        path: "redis-auth"
      - resourceName: "projects/{{ .Values.projectId }}/secrets/{{ .Values.redis.caSecretId }}/versions/latest"
        path: "redis-ca"
---
apiVersion: secret-sync.gke.io/v1
kind: SecretSync
metadata:
  name: order-service-cache
  namespace: {{ .Release.Namespace }}
spec:
  serviceAccountName: {{ include "order-service.name" . }}
  secretProviderClassName: order-service-cache
  secretObject:
    type: Opaque
    data:
      - sourcePath: redis-auth
        targetKey: auth
      - sourcePath: redis-ca
        targetKey: ca.crt
