apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "order-service.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "order-service.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.gcpServiceAccount }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gcpServiceAccount | quote }}
  {{- end }}
automountServiceAccountToken: true
