apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "order-service.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "order-service.labels" . | nindent 4 }}
automountServiceAccountToken: true
