apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: order-service
  namespace: order-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: order-service
      app.kubernetes.io/component: api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
