image:
  repository: europe-west3-docker.pkg.dev/project-03272afe-c622-4c2b-868/order-service/order-service
  tag: sha-placeholder
  pullPolicy: IfNotPresent

projectId: project-03272afe-c622-4c2b-868
region: europe-west3
negName: order-service-production-europe-west3

serviceAccount:
  gcpServiceAccount: order-production-app@project-03272afe-c622-4c2b-868.iam.gserviceaccount.com

replicaCount: 6
cacheTTL: 60s

database:
  host: ""
  port: 5432
  name: orders
  user: order_service
  cidr: 10.190.0.0/16
  secretId: order-production-postgres-password

redis:
  host: ""
  port: 6378
  authSecretId: order-production-redis-auth
  caSecretId: order-production-redis-ca

billingApi:
  cidr: 203.0.113.10/32
  port: 443

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi

autoscaling:
  minReplicas: 6
  maxReplicas: 30
  cpuUtilization: 60
  memoryUtilization: 70
