name: Deploy staging

on:
  workflow_dispatch:

concurrency:
  group: order-service-release-staging
  cancel-in-progress: false

permissions:
  contents: write
  id-token: write

jobs:
  release:
    name: Build and deploy staging
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment: staging
      build_image: true
      image_tag: ${{ github.sha }}
    permissions:
      contents: write
      id-token: write
